const sourceSiteCategories = [
  {
    id: "image-resources",
    label: "图像素材",
    items: [
      { name: "photock", url: "https://photock.jp/", desc: "日本街景、自然风光与城市建筑照片素材。", group: "图片素材" },
      { name: "Pexels", url: "https://www.pexels.com/zh-cn/", desc: "摄影图片与视频素材，可按主题搜索下载。", group: "图片素材" },
      { name: "Negative Space", url: "https://negativespace.co/", desc: "涵盖人物、食物、商业等主题的免费摄影素材。", group: "图片素材" },
      { name: "Unsplash", url: "https://unsplash.com/", desc: "摄影师分享的高清照片，适合配图与设计参考。", group: "图片素材" },
      { name: "Pixabay", url: "https://pixabay.com/", desc: "图片、插画、视频、音乐与音效素材。", group: "图片素材" },
      { name: "Game Icons", url: "https://game-icons.net/", desc: "游戏主题图标，可下载 SVG 和 PNG 格式。", group: "图片素材" },
      { name: "Hello 图床", url: "https://www.helloimg.com/", desc: "上传、管理图片并生成可嵌入网页的外链。", group: "图床分享" },
    ],
  },
  {
    id: "image-editing",
    label: "图像编辑",
    items: [
      { name: "在线拼图", url: "https://fulicat.com/lab/pintu/", desc: "在浏览器中拼接长图、压缩图片和转换格式。", group: "图像处理" },
      { name: "水印去除", url: "https://www.vidmore.com/zh/watermark-remover/", desc: "涂选图片中的水印或物体，自动填补所选区域。", group: "图像处理" },
      { name: "在线抠图", url: "https://www.remove.bg/zh", desc: "自动去除图片背景，导出透明底图片。", group: "图像处理" },
      { name: "Unscreen", url: "https://www.unscreen.com/", desc: "自动移除视频背景，可导出透明背景视频或 GIF。", group: "图像处理" },
      { name: "更改图片颜色", url: "https://changeimagecolor.net/zh/color-replace", desc: "替换图片中的指定颜色，调整相似色与透明度。", group: "图像处理" },
      { name: "图片无损放大", url: "https://bigjpg.com/", desc: "使用 AI 放大插画与照片，减少噪点和锯齿。", group: "图像处理" },
      { name: "AI 扩图", url: "https://www.picsman.ai/zh-cn/tools/ai-enlarge-image", desc: "向画面外延展图片内容，调整图片比例。", group: "图像处理" },
      { name: "Image Tools", url: "https://imagetoolkit.org/zh", desc: "图片压缩、格式转换、编辑与背景移除工具。", group: "图像处理" },
      { name: "Photopea", url: "https://www.photopea.com/", desc: "在线图像编辑器，支持 PSD、XCF 等格式。", group: "图像处理" },
      { name: "TinyPNG", url: "https://tinypng.com/", desc: "智能压缩 PNG、JPEG 与 WebP 图片。", group: "图像处理" },
      { name: "Animated GIF Maker", url: "https://ezgif.com/maker", desc: "用图片或视频制作、裁剪、压缩和编辑 GIF。", group: "图像处理" },
      { name: "Alunapp Photo", url: "https://alunapp.cn/photo/", desc: "照片处理与编辑工具。", group: "图像处理" },
    ],
  },
  {
    id: "file-tools",
    label: "文件工具",
    items: [
      { name: "转换文件工具箱", url: "https://www.aconvert.com/cn/", desc: "转换文档、电子书、图片和音视频文件格式。", group: "格式转换" },
      { name: "iLovePDF", url: "https://www.ilovepdf.com/", desc: "PDF 合并、拆分、压缩、转换与签名。", group: "格式转换" },
      { name: "PdfZap", url: "https://pdfzap.toolooz.com/", desc: "免费在线批量压缩 PDF 文件，全程本地处理以保护隐私。", group: "格式转换" },
      { name: "FreeCompress", url: "https://freecompress.com/zh-cn", desc: "在线压缩图片、视频、音频与文档。", group: "格式转换" },
      { name: "HexEd.it", url: "https://hexed.it/", desc: "在浏览器中查看和编辑文件的十六进制数据。", group: "文件分析" },
      { name: "AB Download Manager", url: "https://abdownloadmanager.com/", desc: "开源多线程下载管理器，支持浏览器集成。", group: "下载工具" },
      { name: "TinyWow", url: "https://tinywow.com/", desc: "PDF、图片、视频转换与编辑工具集合。", group: "通用工具" },
      { name: "Code Beautify", url: "https://codebeautify.org/", desc: "代码格式化、压缩、转换与验证工具。", group: "开发工具" },
      { name: "Unicode 文本转换器", url: "https://qaz.wtf/u/convert.cgi?", desc: "将字母与数字转成可复制的 Unicode 花体字符。", group: "文本处理" },
      { name: "在线工具大全", url: "https://www.lddgo.net/", desc: "提供网络请求、加密解密与正则表达式等在线工具。", group: "通用工具" },
      { name: "FunCipherBox", url: "https://funcipherbox.toolooz.com/", desc: "趣味在线加密解密工具箱，支持多种文本处理方式。", group: "文本处理" },
    ],
  },
  {
    id: "content-creation",
    label: "内容创作",
    items: [
      { name: "Weave Silk", url: "https://weavesilk.com/", desc: "交互式丝绸绘画与视觉创作工具。", group: "绘画工具" },
      { name: "Pixel Beads", url: "https://www.pixelbeads.io/zh-cn", desc: "在线制作像素拼豆图案的创作工具。", group: "像素创作" },
      { name: "MakeBead", url: "https://makebead.com/zh-Hans/maker/pixel-art-editor/", desc: "在线像素画编辑器，可制作拼豆图案。", group: "像素创作" },
    ],
  },
  {
    id: "entertainment",
    label: "影音娱乐",
    items: [
      { name: "爱看机器人", url: "https://www.imoviebot.com/", desc: "搜索电影、电视剧等影视资源。", group: "影视资源" },
      { name: "资源机器人", url: "https://www.ziyuan520.com/", desc: "综合资源检索机器人，可免费查找影视、游戏、软件、音乐和电子书等资源。", group: "影视资源" },
      { name: "ZIP0", url: "https://zip0.com/?r=PFWHX7", desc: "影视聚合搜索与播放，支持选集和切换线路。", group: "影视资源" },
      { name: "SyncTV 文档", url: "https://docs.synctv.wiki/", desc: "SyncTV 多人同步观影工具的安装、部署与使用文档。", group: "影视资源" },
      { name: "GGemu", url: "https://ggemu.com/", desc: "提供复古游戏模拟器与相关游戏资源下载。", group: "游戏资源" },
      { name: "Steam Card Exchange", url: "https://www.steamcardexchange.net/", desc: "查询 Steam 集换式卡牌、徽章与资料背景。", group: "游戏资源" },
      { name: "Radio Garden", url: "https://radio.garden/", desc: "在地球仪上收听全球各地的电台。", group: "音乐电台" },
      { name: "Tunefind", url: "https://www.tunefind.com/", desc: "查询电影、电视剧和游戏中出现的歌曲与配乐。", group: "音乐电台" },
      { name: "怀旧游戏博物馆", url: "https://rgm.games/", desc: "保护、展示与在线体验经典电子游戏的非营利项目。", group: "游戏资源" },
      { name: "Fuun", url: "https://fuun.fun/", desc: "在线小游戏与互动体验平台。", group: "游戏资源" },
      { name: "AHA Music", url: "https://aha-music.com/", desc: "识别歌曲并搜索音乐信息。", group: "音乐电台" },
    ],
  },
  {
    id: "ebooks",
    label: "电子书籍",
    items: [
      { name: "书格", url: "https://www.shuge.org/", desc: "古籍、书画与历史文献的数字化影像。", group: "古籍文献" },
      { name: "识典古籍", url: "https://www.shidianguji.com/", desc: "古籍 OCR 识别与全文检索平台。", group: "古籍文献" },
      { name: "中国哲学书电子化计划", url: "https://ctext.org/zhs", desc: "先秦两汉文献全文数据库。", group: "古籍文献" },
      { name: "马克思主义文库", url: "https://www.marxists.org/chinese/index.html", desc: "马克思主义相关著作、文章与历史文献。", group: "专题文献" },
      { name: "Z-Library", url: "https://zh.zlib.by/", desc: "电子书与学术文献检索。", group: "电子书库" },
      { name: "Z-Library 镜像", url: "https://zlib.wwwnav.com/", desc: "Z-Library 电子书资源的备用入口。", group: "电子书库" },
      { name: "Project Gutenberg", url: "https://www.gutenberg.org/", desc: "公共版权电子书免费下载与在线阅读。", group: "电子书库" },
      { name: "Liber3", url: "https://liber3.eth.limo/", desc: "去中心化电子书搜索与推荐。", group: "电子书库" },
    ],
  },
  {
    id: "library",
    label: "图书馆藏",
    items: [
      { name: "WorldCat", url: "https://search.worldcat.org/zh-cn", desc: "查询全球图书馆的书目与馆藏信息。", group: "馆藏查询" },
      { name: "国家图书馆", url: "https://www.nlc.cn/web/index.shtml", desc: "国家图书馆数字资源、公开课与在线展览门户。", group: "国家图书馆" },
      { name: "文津搜索", url: "http://find.nlc.cn/", desc: "国家图书馆的馆藏与文献检索入口。", group: "国家图书馆" },
      { name: "中国出版物数据", url: "https://pdc.capub.cn/", desc: "查询出版物版本、ISBN 与在版编目数据。", group: "出版数据" },
      { name: "Sci-Hub", url: "https://www.sci-hub.in/", desc: "学术论文检索与全文获取。", group: "学术论文" },
      { name: "HathiTrust", url: "https://www.hathitrust.org/", desc: "高校图书馆联合数字典藏，可全文检索。", group: "馆藏查询" },
    ],
  },
  {
    id: "learning",
    label: "在线学习",
    items: [
      { name: "Open Culture", url: "https://www.openculture.com/", desc: "免费电子书、公开课、电影与有声书索引。", group: "在线教程" },
      { name: "Oeasy", url: "https://oeasy.net/", desc: "编程、设计与多媒体教程站。", group: "在线教程" },
      { name: "打字鸭", url: "https://daziya.com/", desc: "盲打指法、拼音与英文打字练习平台。", group: "在线教程" },
      { name: "Qwerty Learner", url: "https://qwertylearner.cn/", desc: "单词与键盘打字练习工具。", group: "在线教程" },
      { name: "菜鸟教程", url: "https://www.runoob.com/", desc: "编程语言与开发技术学习教程。", group: "在线教程" },
    ],
  },
  {
    id: "encyclopedia",
    label: "综合百科",
    items: [
      { name: "灰机 wiki", url: "https://www.huijiwiki.com/wiki/%E9%A6%96%E9%A1%B5", desc: "游戏、动漫与兴趣主题的中文百科社区。", group: "综合百科" },
      { name: "Fandom", url: "https://www.fandom.com/", desc: "由爱好者共同维护的游戏与影视百科。", group: "综合百科" },
      { name: "wikiHow", url: "https://www.wikihow.com/Main-Page", desc: "图文步骤式的生活与技能操作指南。", group: "综合百科" },
      { name: "Avibase", url: "https://avibase.bsc-eoc.org/avibase.jsp", desc: "全球鸟类物种数据库与分布信息。", group: "专业资料" },
      { name: "Funes", url: "https://funes.world/", desc: "科幻与奇幻作品信息库。", group: "专业资料" },
      { name: "MuscleWiki", url: "https://musclewiki.com/zh-cn", desc: "按肌肉部位查询健身动作与演示。", group: "专业资料" },
      { name: "SaDuck", url: "https://saduck.top/", desc: "公务员考试知识库、考点解析与备考工具。", group: "专业资料" },
      { name: "Wolfram Alpha", url: "https://www.wolframalpha.com/", desc: "数学计算、数据分析与知识问答引擎。", group: "科学工具" },
      { name: "LLM Live Rankings", url: "https://rank.svenrogue.top/", desc: "全球大模型实时热度排行榜。", group: "科学工具" },
    ],
  },
  {
    id: "culture-science",
    label: "文化科学",
    items: [
      { name: "Internet Archive", url: "https://archive.org/", desc: "网页快照、书籍、影音与软件的数字档案馆。", group: "历史文化" },
      { name: "全历史", url: "https://www.allhistory.com/", desc: "以时间轴与关系图谱呈现历史事件与人物。", group: "历史文化" },
      { name: "Old Maps Online", url: "https://www.oldmapsonline.org/zh", desc: "检索与浏览全球历史地图馆藏。", group: "历史文化" },
      { name: "FemRes", url: "https://www.femres.org/", desc: "女性主义书籍、影视、播客与学术资料索引。", group: "历史文化" },
      { name: "HerStory", url: "https://herstory.top/", desc: "女性人物故事与历史贡献资料。", group: "历史文化" },
      { name: "Shape of World", url: "https://shapeof.world/", desc: "地理数据可视化与世界地图展示。", group: "科学工具" },
      { name: "Scale of Universe", url: "https://scaleofuniverse.com/zh", desc: "宇宙尺度可视化，从量子到星系。", group: "科学工具" },
      { name: "100,000 Stars", url: "https://stars.chromeexperiments.com/", desc: "银河系星图 3D 可视化体验。", group: "科学工具" },
      { name: "故宫博物院院刊", url: "https://www.dpm.org.cn/yygg.html", desc: "故宫博物院学术期刊与研究资料。", group: "历史文化" },
      { name: "数字敦煌", url: "https://www.e-dunhuang.com/index.htm", desc: "敦煌石窟与壁画的数字化展示。", group: "历史文化" },
    ],
  },
  {
    id: "developer",
    label: "开发工具",
    items: [
      { name: "Cloudflare", url: "https://www.cloudflare.com/", desc: "提供网络安全、域名与网站部署服务。", group: "基础设施" },
      { name: "GitHub", url: "https://github.com/", desc: "托管代码仓库、协作开发与开源项目。", group: "基础设施" },
      { name: "Greasy Fork", url: "https://greasyfork.org/zh-CN", desc: "发布和获取浏览器用户脚本。", group: "基础设施" },
      { name: "Carbon", url: "https://carbon.now.sh/", desc: "代码截图美化工具，支持多种主题与语言。", group: "开发工具" },
      { name: "Coolors", url: "https://coolors.co/", desc: "配色方案生成与调色板管理工具。", group: "开发工具" },
      { name: "VIA", url: "https://usevia.app/", desc: "配置兼容键盘的键位、宏与灯光。", group: "开发工具" },
      { name: "AlternativeTo", url: "https://alternativeto.net/", desc: "按用户评价查找软件与服务的替代方案。", group: "导航工具" },
    ],
  },
  {
    id: "resource-navigation",
    label: "资源导航",
    items: [
      { name: "FMHY", url: "https://fmhy.net/beginners-guide", desc: "免费资源与工具的大型索引合集。", group: "资源导航" },
      { name: "电子书宝藏导航", url: "https://shu.baozangdh.com/", desc: "书籍与电子阅读资源导航。", group: "资源导航" },
      { name: "影视宝藏导航", url: "https://tv.baozangdh.com/", desc: "影视资源导航。", group: "资源导航" },
      { name: "二次元宝藏导航", url: "https://acg.baozangdh.com/", desc: "二次元资源导航。", group: "资源导航" },
      { name: "游戏宝藏导航", url: "https://game.baozangdh.com/", desc: "游戏资源导航。", group: "资源导航" },
      { name: "AI导航123", url: "https://aidh123.com/", desc: "人工智能工具与资源导航。", group: "资源导航" },
    ],
  },
  {
    id: "network-testing",
    label: "网络测试",
    items: [
      { name: "iPure", url: "https://ipure.dev/", desc: "IP 纯净度检测与代理识别。", group: "网络测试" },
      { name: "CleanIP", url: "https://cleanip.io/", desc: "IP 地址质量检测与黑名单查询工具。", group: "网络测试" },
      { name: "IPPure", url: "https://ippure.com/", desc: "IP 纯净度分析与代理检测服务。", group: "网络测试" },
      { name: "Downdetector", url: "https://downdetector.com/", desc: "查询各类网络服务的故障与中断状态。", group: "网络测试" },
      { name: "Fast.com", url: "https://fast.com/", desc: "Netflix 提供的网络下载速度测试。", group: "网络测试" },
    ],
  },
  {
    id: "community",
    label: "社区记录",
    items: [
      { name: "NeoDB", url: "https://neodb.social/", desc: "记录和分享图书、影视、音乐与游戏。", group: "影音记录" },
      { name: "IMDb", url: "https://www.imdb.com/", desc: "查询电影、电视剧、演员资料与观众评分。", group: "影音记录" },
      { name: "Bangumi", url: "https://bgm.tv/", desc: "记录和查询动画、游戏、音乐与图书内容。", group: "影音记录" },
      { name: "RIP", url: "https://rip.abloom.site/bei", desc: "纪念与墓志铭记录平台。", group: "其他记录" },
      { name: "FlowUs", url: "https://flowus.cn/", desc: "整理笔记、文档、项目与个人知识内容。", group: "知识管理" },
      { name: "VibeCafé", url: "https://vibecafe.ai/", desc: "交流 AI 编程、作品展示与相关资源的社区。", group: "技术社区" },
      { name: "Hacker News 播客", url: "https://hacker-news.agi.li/", desc: "科技新闻与 Hacker News 话题播客。", group: "技术社区" },
      { name: "九墨日记", url: "https://jiumo-diary.com/", desc: "记录日常文字与个人生活的在线日记。", group: "个人记录" },
    ],
  },
  {
    id: "living",
    label: "生活服务",
    items: [
      { name: "租房地图", url: "https://web.house2048.cn/", desc: "聚合豆瓣、贝壳等租房信息，在地图展示房源与通勤路线。", group: "租房工具" },
      { name: "城市租房生存指南", url: "https://zufang.ababtools.com/", desc: "面向租房新手的省钱、看房、签约与避坑指南。", group: "租房工具" },
      { name: "鸭小租", url: "https://yaxiaozu.ababtools.com/", desc: "面向租客的租房网址导航，汇集找房与生活服务入口。", group: "租房工具" },
    ],
  },
  {
    id: "accounts",
    label: "账户安全",
    items: [
      { name: "Dynadot", url: "https://www.dynadot.com/zh", desc: "域名注册、网站服务与网络资源管理。", group: "域名邮箱" },
      { name: "Proton Mail", url: "https://proton.me/mail", desc: "Proton 加密邮箱服务。", group: "域名邮箱" },
      { name: "Temp Mail", url: "https://temp-mail.org/", desc: "临时匿名邮箱，用于注册与接收验证邮件。", group: "域名邮箱" },
      { name: "Have I Been Pwned", url: "https://haveibeenpwned.com/", desc: "检查邮箱或密码是否在数据泄露中出现。", group: "安全工具" },
      { name: "Account Killer", url: "https://www.accountkiller.com/", desc: "各类网站账号注销与删除指南。", group: "账号管理" },
    ],
  },
  {
    id: "subscriptions",
    label: "订阅服务",
    items: [
      { name: "Dodo Payments", url: "https://app.dodopayments.com/", desc: "数字产品支付处理与订阅管理平台。", group: "支付服务" },
      { name: "PriceAI", url: "https://priceai.cc/", desc: "对比 AI 订阅、官方 API 和中转 API 的价格、来源、库存与更新时间。", group: "AI 订阅" },
      { name: "WildAI", url: "https://bewild.ai/?code=JDYR4ATU", desc: "ChatGPT、Claude 与 X 等服务的订阅代购。", group: "AI 订阅" },
      { name: "DaseinAI", url: "https://www.daseinai.xyz/register?aff=VWHM8SMXYMLH", desc: "AI 模型 API 接入与中转服务。", group: "AI 订阅" },
      { name: "ProAIAPI", url: "https://proaiapi.vip/register?aff=WsJ0", desc: "AI 模型 API 接入与中转服务。", group: "AI 订阅" },
      { name: "Dragon3", url: "https://newapi.dragon3api.com/sign-up?aff=aEBR", desc: "AI 模型 API 接入与中转服务。", group: "AI 订阅" },
      { name: "大象网络", url: "https://dx.elphantroute.com/app#/register?code=n5KEb6em", desc: "提供网络代理订阅服务。", group: "网络订阅" },
      { name: "SakuraCat", url: "https://sakuracat-1.com/register?code=Kuc1kZi6", desc: "提供网络代理订阅服务。", group: "网络订阅" },
    ],
  },
];

const categoryRules = [
  { id: "image-resources", label: "图像素材", match: (category) => category.id === "image-resources" },
  { id: "image-editing", label: "图像编辑", match: (category) => category.id === "image-editing" },
  { id: "file-tools", label: "文件工具", match: (category) => category.id === "file-tools" },
  { id: "content-creation", label: "内容创作", match: (category) => category.id === "content-creation" },
  { id: "entertainment", label: "影音娱乐", match: (category) => category.id === "entertainment" },
  { id: "ebooks", label: "电子书籍", match: (category) => category.id === "ebooks" },
  { id: "library", label: "图书馆藏", match: (category) => category.id === "library" },
  { id: "learning", label: "在线学习", match: (category) => category.id === "learning" },
  { id: "encyclopedia", label: "综合百科", match: (category) => category.id === "encyclopedia" },
  { id: "culture-science", label: "文化科学", match: (category) => category.id === "culture-science" },
  { id: "resource-navigation", label: "资源导航", match: (category) => category.id === "resource-navigation" },
  { id: "developer", label: "开发工具", match: (category) => category.id === "developer" },
  { id: "network-testing", label: "网络测试", match: (category) => category.id === "network-testing" },
  { id: "community", label: "社区记录", match: (category) => category.id === "community" },
  { id: "living", label: "生活服务", match: (category) => category.id === "living" },
  { id: "accounts", label: "账户安全", match: (category) => category.id === "accounts" },
  { id: "subscriptions", label: "订阅服务", match: (category) => category.id === "subscriptions" },
];

const siteCategories = categoryRules.map((rule) => ({
  id: rule.id,
  label: rule.label,
  items: sourceSiteCategories.flatMap((category) => category.items.filter((item) => rule.match({ ...category, group: item.group }))),
})).filter((category) => category.items.length > 0);

const categorizedItems = siteCategories.flatMap((category) => category.items);
const sourceItems = sourceSiteCategories.flatMap((category) => category.items);
if (categorizedItems.length !== sourceItems.length) throw new Error(`分类重组遗漏站点：${sourceItems.length} -> ${categorizedItems.length}`);

const siteSearchIndex = siteCategories.flatMap((category) =>
  category.items.map((item) => ({
    category,
    item,
    haystack: `${item.name} ${item.desc} ${category.label}`.toLowerCase(),
  })),
);
